### ISSUE TITLE
[ssl-issues] SSL handshaking fails due to SNI issue in requests

### ISSUE THREAD

**Issue by black-perl** [coursera-dl/coursera-dl#329]
Due to this https://github.com/kennethreitz/requests/pull/1347 , the SNI issue in requests, on Ubuntu/Debian systems SSL handshaking fails and so as the courera-dl.
But doing this workaround in a vitualenv make coursera-dl work : https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484
 I think there should be built-in support for this situation.

**Comment by sergshabal** [comment]
Hi! Do you know how can I fix this quickly?

**Comment by rbrito** [comment]
Hi.

Can you post here the integral messages (with the `--debug` option used), so that we can evaluate what the problem may be?

Since you didn't specify any further, please take a look at my comments https://github.com/coursera-dl/coursera/issues/330#issuecomment-89707998 and, especially, https://github.com/coursera-dl/coursera/issues/330#issuecomment-89708466


Hope this helps,

Rogério.

**Comment by adamors** [comment]
This helped me: https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
