### ISSUE TITLE
Unable to download/find new courses

### ISSUE THREAD

**Issue by ma-ver-ick** [coursera-dl/coursera-dl#387]
It seems coursera has a new format? As I'm unable to download the human-computer-interaction, but able (in the past) to download other courses.

```bash
> coursera-dl -u XXX -p XXX human-computer-interaction --debug
root[main] Downloading class: human-computer-interaction
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file XXX into memory.
root[get_cookies_from_cache] Loaded cookies from XXX
root[login] Initiating login.
root[login] Cleared .coursera.org cookies.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /human-computer-interaction HTTP/1.1" 404 None
root[login] 404 Client Error: Not Found
root[main] Could not find class: human-computer-interaction
```

Is this a known problem?

**Comment by balta2ar** [comment]
What's the URL of the class? Can you open it in the browser?

**Comment by ma-ver-ick** [comment]
The url is https://www.coursera.org/learn/human-computer-interaction/home/welcome and it opens perfectly in the browser.

**Comment by balta2ar** [comment]
That's an "On Demand" course. Please add ` --on-demand` option to coursera-dl command line and try again.

Side note to @rbrito: maybe we should automatically check:
1. Is this a regular course?
2. Is this an on-demand course?
3. Fail is neither worked?

**Comment by ma-ver-ick** [comment]
Ah, that worked - thanks!
Maybe add it to the Troubleshooting?

"If you get an error like Could not find class: <CLASS_NAME>, then:"
-> * Maybe it's an on-demand course? Please recheck.

**Comment by balta2ar** [comment]
Yes, at least that could be done. However I think it is better to automate the check if possible. Let's see what @rbrito has to say on this one.

**Comment by mxamin** [comment]
@balta2ar, I don't think this process can be automated (for now). *Coursera* team is working on developing an API for third party applications but strongly suggests that developers don't use it for production purposes because it may change anytime without any warning that in result will break the users code. And without the API we can not know which type the course is, by only looking at its name.

**Comment by balta2ar** [comment]
@mxamin I know this is not 100% reliable but we at least we can try to download the course as if it is 1) a regular course 2) on-demand course. If nothing works, report an error. What are the downsides of this approach?

**Comment by mxamin** [comment]
@balta2ar I didn't think of it that way, it is possible but because it is an unusual way to determine the type of the course, I think it's better to leave it to @rbrito to decide what to do.

**Comment by rbrito** [comment]
Dear people, I think that this is a serious bug that we are facing (yes, after correctness problems, I think that usability of programs---especially for programs meant to be used by non-specialist people---is of high importance).

@balta2ar, I had already thought about "trying everything" before, but I was too lazy and didn't implement it, because I didn't anticipate that this would be a common problem for our users.

I did something like that "try everything" before in my outdated personal fork of edx-dl: https://github.com/rbrito/edx-dl-old-fork/commit/1e8d5e8d97b26300e9b14ba726380ed711e41fa6

I think that we can act in two fronts here:

* Document that new courses have a new URL format (so that users may know if they are using an ondemand course or not---e.g., URLs have a different format, courses offerings aren't numbered etc).
* Implement this "try everything" strategy.

And, perhaps, if it proves to be useful, simply kill the `--on-demand` option and try everything in a future version, as that's less of a cognitive burden on the user and we should strive to a "just works" program.

I'm marking this with the "easy-to-fix" tag, since each of the steps are quite small and I would welcome anybody to attack the problem.

**Comment by achaleus** [comment]
Hello I tried using --on-demand still downloading is not working showing above mentioned error.. link is
https://class.coursera.org/hardwaresec-004

**Comment by balta2ar** [comment]
@achaleus The course you mentioned is not "on demand". Try removing the option. If it's still not working... I don't know, wild guess, did you accept "honor of code" page? This is the page that pops up when you visit the course for the first time.

**Comment by achaleus** [comment]
coursera-dl -u xxxxxx@gmail.com -p xxxxxxx --preview https://class.coursera.org/cplusplus4c-002/lecture/preview --debug
root[main] Downloading class: https://class.coursera.org/cplusplus4c-002/lecture/preview
root[get_syllabus_url] Using preview mode with page: https://class.coursera.org/https://class.coursera.org/cplusplus4c-002/lecture/preview/lecture/preview
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /https://class.coursera.org/cplusplus4c-002/lecture/preview/lecture/preview HTTP/1.1" 404 None
root[get_page] Error 404 Client Error: Not Found getting page https://class.coursera.org/https://class.coursera.org/cplusplus4c-002/lecture/preview/lecture/preview
root[main] HTTPError 404 Client Error: Not Found


any help where I went wrong

**Comment by achaleus** [comment]
coursera-dl -u xxxx@gmail.com -p xxxxx https://class.coursera.org/introtoelectronics-002 --debug
root[main] Downloading class: https://class.coursera.org/introtoelectronics-002
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file C:\Users\UCHR1-~1\AppData\Local\Temp\uchr1-vinaykumar_coursera_dl_cache\cookies\mvinay73@gmail.com.txt into memory.
root[get_cookies_from_cache] Loaded cookies from C:\Users\UCHR1-~1\AppData\Local\Temp\uchr1-vinaykumar_coursera_dl_cache\cookies\mvinay73@gmail.com.txt
root[login] Initiating login.
root[login] Cleared .coursera.org cookies.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /https://class.coursera.org/introtoelectronics-002 HTTP/1.1" 404 None
root[login] 404 Client Error: Not Found
root[main] Could not find class: https://class.coursera.org/introtoelectronics-002

I unable to download any of courses... I am getting same error mentioned above

**Comment by rbrito** [comment]
@ma-ver-ick, please send a pull request against our README or edit the wiki with the information that you found to be useful.

**Comment by victorwestmann** [comment]
@rbrito just an idea: maybe we could put some error message suggesting the user to use --on-demand extra argument. Just a thought. :smile:

**Comment by rbrito** [comment]
@victorwestmann, Do you mean something like this:

https://github.com/coursera-dl/coursera-dl/blob/master/coursera/cookies.py#L86-L88

?

**Comment by victorwestmann** [comment]
hehehe yup. :baby:

**Comment by rbrito** [comment]
@achaleus, I can't find your message here (perhaps you edited it), but you were specifying the entire URL of the course.  You have to specify only the course name, like in:

```
coursera-dl -u xxxx@gmail.com -p xxxxx introtoelectronics-002
```

I wonder if our documentation isn't clear on these matters :(
