### ISSUE TITLE
Is it possible to specify video format to download like 360p or 1080p?

### ISSUE THREAD

**Issue by dhawalbanker** [coursera-dl/coursera-dl#389]
Like the option that's present in edx-dl, where you can specify format by argument

-f [height<=?360p]

**Comment by mxamin** [comment]
@dhawalbanker, as far as I know, *most* of regular courses don't categorize their videos in different formats, they often prepare their course videos in **one** specific format, therefor this option (if implemented in future) has no use for this type of courses.

But about on-demand courses everything changes :), they all categorize their videos in 360p, 720p and sometimes 1080p formats which can be downloaded based on users choice. This feature you are asking was one of my TODO items since I added *on-demand* download feature, but I didn't have time to add it. If you have intention to work on adding this feature, I can give you the resources I have found already about this matter (actually it's pretty easy).

**Comment by rbrito** [comment]
@dhawalbanker, as @mxamin wrote, I'm only aware of videos being presented in 540p for regular courses (some glitches on Coursera's side once exposed some 720p videos for some courses that I was taking, like "The History of Rock, part I", but those were exceptions).

As I myself use `coursera-dl` for archival purposes, I want to have all videos in 540p as much as I can, as that is a very good balance between size, resolution etc. For courses on edX, since you have to either use 480p or 720p and the sizes go up drastically, I stick with 480p (I have problems reading stuff in 360p). 

With on-demand courses on coursera, we have options of specifying the resolution, as you may have seen that.  If I understand it correctly (and @mxamin, please correct me if I am wrong) the courses are described in JSON format and I may tackle that, since I don't particularly want 720p videos right now. ;)

@mxamin, if you want to deal with this, I can assign this bug to you, OK?

**Comment by mxamin** [comment]
ok, no problem, I can do that.

**Comment by rbrito** [comment]
I'll take a look at this, as it is getting on my nerves. ;)

OTOH, if anybody beats me to it, please, submit pull requests. :)

**Comment by Domo1017** [comment]
@rbrito did you find any solution ?

**Comment by rbrito** [comment]
Use the `--video-resolution` option. BTW, I guess that we need to add that some courses *may* (or may not) support 1080p in the help message...

**Comment by TejVed** [comment]
@rbrito How to use --video-resolution option? Like how to implement it?
