### ISSUE TITLE
Is this bug?

### ISSUE THREAD

**Issue by linpackzh** [coursera-dl/coursera-dl#393]
When I download course 'financial-engineering-1', it dumps the following error message:

Traceback (most recent call last):
  File "d:\coursera-dl\coursera-dl\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "d:\coursera-dl\coursera-dl\coursera\coursera_dl.py", line 1055, in main
    result = download_on_demand_class(args, class_name)
  File "d:\coursera-dl\coursera-dl\coursera\coursera_dl.py", line 1031, in downl
oad_on_demand_class
    args.resume
  File "d:\coursera-dl\coursera-dl\coursera\coursera_dl.py", line 561, in downlo
ad_lectures
    downloader.download(url, lecfn, resume=resume)
  File "d:\coursera-dl\coursera-dl\coursera\downloaders.py", line 50, in downloa
d
    self._start_download(url, filename, resume)
  File "d:\coursera-dl\coursera-dl\coursera\downloaders.py", line 366, in _start
_download
    f = open(filename, 'ab') if resume else open(filename, 'wb')
IOError: [Errno 2] No such file or directory: u'financial-engineering-1\\07_intr
oduction-to-mortgage-mathematics-and-mortgage-backed-securities\\01_introduction
-to-mortgage-mathematics-and-mortgage-backed-securities\\01_introduction-to-mort
gage-mathematics-and-mortgage-backed-securities.mp4'

How to solve it? Thanks!

**Comment by mxamin** [comment]
I don't know if we can categorize it as a bug or not, any how the reason of this error is because of the length of the file path. As you may know, in most operating systems (Windows, Linux, ...) the length of file path can not exceed 255 characters, and if it does it will throw an exception. This is what happened in your case.
I have faced the same problem when I was downloading *Calculus1* course, where by using `--path` option and choosing the shorten path (in my case `--path ~`), I could overcome this problem.
May be it will also solve your problem, try it.

**Comment by linpackzh** [comment]
Thanks for your quick reply. --path option works. It might be not a bug. 
Thanks!
