### ISSUE TITLE
logging in with an account that was created via OAuth?

### ISSUE THREAD

**Issue by EMCP** [coursera-dl/coursera-dl#397]
My Coursera profile was created with OAuth authorization (aka log me in with Facebook).

It seems I cannot login to Coursera with my email and password.. only via the OAuth button.  This script doesn't seem to mention how to use it in conjunction with Facebook created Coursera profiles.  Is this possible?

**Comment by rbrito** [comment]
Hi, @EMCP.

No, we have not yet implemented other authentication methods. One thing that you can use as a workaround is to log into your Coursera account, export your cookies to a cookies.txt file and let coursera-dl use them with the option `-c`.

Hope this helps,

Rogério.

**Comment by rbrito** [comment]
Regarding a proper implementation, I would welcome any patches to do that.

**Comment by rbrito** [comment]
@EMCP, did the trick of using the cookies file work for you?

**Comment by balta2ar** [comment]
For those who might want to start implementing this, could anyone provide some technical links with description on how to support that?

**Comment by EMCP** [comment]
@rbrito I'll have to delay retrying this for later this weekend.  Sorry it's taking a while.

**Comment by rbrito** [comment]
@balta2ar, I once used oauth with Twitter's API and it was almost painless, *but* it required 4 "magic strings" that we may or may not distribute with the code (since our code is open and everybody can see it).

Of course, I forgot the finer details, but I would start now with these links:

* https://requests-oauthlib.readthedocs.org/en/latest/
* https://cloud.google.com/appengine/docs/python/oauth/

The second URL teaches the basic concepts, which is something that I wished that I had read when I first toyed with oauth. :)

**Comment by Nannooskeeska** [comment]
I attempted the cookie workaround and it did not work for me.

**Comment by terencechow** [comment]
For people coming to this page in the future, you can go to your settings delink your facebook account and set a password to use coursera-dl
