### ISSUE TITLE
fix the build status button (on the project front page)

### ISSUE THREAD

**Issue by victorwestmann** [coursera-dl/coursera-dl#399]
I might be wrong. :)
But I believe the error is in the URL address contained in the button:

Today it points to: https://travis-ci.org/coursera-dl/coursera
I belive it should point to:  https://travis-ci.org/coursera-dl/coursera-dl

:+1:

**Comment by rbrito** [comment]
I tried doing some tests like that, but I couldn't get things working. I need some help here, since I followed the same procedures with `edx-dl` and there everything works, while here it stopped working some time ago (don't really know very much why).

Can you make things work in your local clone? Please, feel free to send pull requests, as that's annoying.

**Comment by victorwestmann** [comment]
It worked! You should just change the URL (a) for the (b) :-)

(a) https://travis-ci.org/coursera-dl/coursera
(b) https://travis-ci.org/coursera-dl/coursera-dl

And voilá!

**Comment by victorwestmann** [comment]
Working on it right now (pull request pending and opened a ticket under the path https://github.com/travis-ci/travis-ci/issues/4775#issuecomment-139430859 )

**Comment by rbrito** [comment]
Thanks for the investigation/detective work! That's really appreciated!
