### ISSUE TITLE
Udemy Downloader

### ISSUE THREAD

**Issue by d4me94** [coursera-dl/coursera-dl#418]
Hello Sir,
                Please Make An Udemy Course Downloader Like Coursera-dl..Coursera-dl Is Extremely Good Becoz It Is Able To Download Complete Course Like Videos,Texts Etc. I Know There Is A Script Named As Udemy-dl (https://github.com/nishad/udemy-dl-windows) But That Script Is Only To Download Videos After That The Task Of Downloading Course Materials Like PDF,TXT Etc. Goes Very Painful..I Asked From Nishad About This But He Denied By Saying That There Are No Plans Currently To Implement These Features..If You Can Then Please Make A Complete Udemy Downloader Like Coursera-dl Plzzzzzzzz. Or Atleast Tell Us A Way Or Tutorial That We Can Modify Udemy-dl Like Your Coursera-dl That It Can Download Complete Course Please...Thank You

**Comment by yceron** [comment]
+1 to an Udemy Downloader

**Comment by nishad** [comment]
Both `udemy-dl` python package (https://github.com/nishad/udemy-dl), and its windows standalone binaries (https://github.com/nishad/udemy-dl-windows) are designed as ***a utility to download videos from udemy for personal offline use***. I'm maintaining this packages since the original repository is taken down via DMCA. I'm supporting existing users with fixes. I personally doesn't use this script. I'll only provide bug fixes for a time being, as I believe `udemy-dl` ***scripts*** doesn't infringe any udemy.com copyrights.

There are no plan to extend this tool to be something for making complete copies of udemy courses. This tool is not intended to infringe any copyrights of udemy. As the project's description, this will only help to get ***videos*** for personal offline use. Mainly due to bandwidth limitations of users from many developing countries. Please pay for the courses and respect udemy's business model as well.

Widows standalone binaries are provided to help windows users to avoid the pain of installing Python and and all dependencies. Which also helps basic users from debugging python related issues. 

For the same reason I'm maintaining windows binaries of `coursera-dl` as well (https://github.com/nishad/coursera-dl-windows).

:sake: kanpai :)

**Comment by rbrito** [comment]
Hi.

I see that youtube-dl has been offering downloads from udemy for some time now. Perhaps you guys would like to test it to see if it suits your needs?

**Comment by rbrito** [comment]
Hi.

Since we had no feedback from the users, I assume that the alternative programs are working fine.

I'm closing this issue, then.

Rogério Brito.
