### ISSUE TITLE
problems with new courses

### ISSUE THREAD

**Issue by amirj** [coursera-dl/coursera-dl#424]
running the following code:
```
coursera-dl -u <user> -p <pass> ml-foundations
```
raises the following exception:
```
Logging in as 'amir.jadidi@yahoo.com'...
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 648, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 136, in login
    raise Exception("Unknown class %s" % className)
Exception: Unknown class ml-foundations
```
what's the problem?
here is the class's page: https://www.coursera.org/learn/ml-foundations/

**Comment by rbrito** [comment]
Please, for the moment, use the zip/tarball from our master repository. I am taking the same specialization (but on the 2nd course) and it works perfectly for me.

I will upload a new version to PyPI, so that people will be able to continue using the regular `pip install coursera` command.

It's just that I'm living though very hard times with a *very* close family member having cancer and that has prevented me from "playing with computers" (including updating my projects). The meaning of life has changed way too much for me in the last few months...

Hope this helps,

Rogério.

**Comment by amirj** [comment]
Dear Rogério,
I'm sorry for this situation. I believe that you are the man that improve the meaning of life.
I wish happy and health for you and your family.
