### ISSUE TITLE
How to get .srt of different language?

### ISSUE THREAD

**Issue by ValenW** [coursera-dl/coursera-dl#427]
This script is usefal! Thanks a lot!
It download the .srt file in English by default, how can I download the Chinese version? :)

**Comment by ratijas** [comment]
as you can see from 'help': `-sl SUBTITLE_LANGUAGE` ("zh-cn" in your case)

but be aware that for some reason there's a comment in the code saying that it will be deprecated.
```python
    group_basic.add_argument('-sl',  # FIXME: deprecate this option
                             '--subtitle-language',
                             dest='subtitle_language',
                             action='store',
                             default='en',
                             help='Choose language to download subtitles. (Default: en)')
```
if specified language is not available for some video, script will fall back to english.

**Comment by ValenW** [comment]
got it, thanks~

**Comment by rbrito** [comment]
Hi.

On Dec 11 2015, ratijas wrote:
> but be aware that for some reason there's a comment in the code saying
> that it will be deprecated.

No, the selection of languages are not going away. See below.

>     group_basic.add_argument('-sl',  # FIXME: deprecate this option

I put this comment there because I want to deprecate the short options that
have two letters, as they are aesthetically ugly for someone that is used to
the GNU-style of parsing options and because they may confuse the parsing
made by the argparse module.

(...)
> if specified language is not available for some video, script will fall
> back to english.

Another thing that is on my todo list is to encode/indicate the language of
the subtitle in the name of the file, since this will allow the users to
download more than one subtitle. For example:

* 01-An_awesome_lecture.en.srt
* 01-An_awesome_lecture.fr.srt
* 01-An_awesome_lecture.pt.srt

Decent video players are able to detect such subtitles and use them
appropriately (e.g., mpv, vlc etc.).

If anybody wants to go ahead and implement this before I do, by all means,
go ahead. This is semi-trivial to do.


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by ratijas** [comment]
@rbrito nice to hear that.  then i'm gonna do some pull request soon.

**Comment by balta2ar** [comment]
Looks like the original issue is solved. Implementing indication of language in subtitle file name is out of the scope of this issue. Contributions are welcome.

**Comment by rbrito** [comment]
This is already implemented in our head version (and also published to pypi). Please test it.

**Comment by zuanzuan1992** [comment]
--subtitle-language zh-CN
