### ISSUE TITLE
unrecognized arguments 

### ISSUE THREAD

**Issue by AhmedA-del** [coursera-dl/coursera-dl#456]
trying to download learning how to learn course 
https://www.coursera.org/learn/learning-how-to-learn
after adding on-demand it says:
unrecognized arguments :learning-how-to-learn
thanks for this amazing tool!! 
hope it works with me ^_^

**Comment by balta2ar** [comment]
There must be something wrong with the arguments that you pass to the script.

**Comment by AhmedA-del** [comment]
coursera-dl -u username -p password --on-demand learning-how-to-learn

note that I write the user name not the email 
and it contains space

**Comment by balta2ar** [comment]
Try this: `coursera-dl -u 'Your User Name' -p 'Your Password' learning-how-to-learn`

**Comment by AhmedA-del** [comment]
same thing

**Comment by balta2ar** [comment]
Show me the exact command line (excluding name and password, but keep the spaces) and the output.

**Comment by rbrito** [comment]
Hi, @AhmedA-del.

If you are not using an e-mail, I  don't know what kind of authentication you are using with Coursera.

I hear that they have some ways to authenticate with Facebook (and possibly other sites), but this would require implementation of OAUTH(2) authentication, and we don't have that at the moment (contributions would be welcome).

It would, perhaps, be useful also if you mentioned how you registered with coursera, besides the command-line *and* the output with the `--debug` command-line option, like @balta2ar mentioned.

Hope this helps,

Rogério.

**Comment by AhmedA-del** [comment]
coursera-dl -u username -p password --on-demand learning-how-to-learn 
and the output : 
--on-demand option is deprecated and is not required anymore. Do not use this op
tion. It will be removed in the future.
Downloading class: learning-how-to-learn
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/learning-how-to-
learn
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/learning-how-to-lea
rn (38534 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering video URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
Proceeding with download of resolution 540p of <mGhggl_JEeSfFCIACxcQxA>.
Gathering subtitle URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
Gathering transcript URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
Traceback (most recent call last):
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\cookies.py", line 91, in login
    r.raise_for_status()
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://clas
s.coursera.org/learning-how-to-learn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: learning-how-to-learn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ahmed\AppData\Local\Programs\Python\Python35-32\Scripts\courser
a-dl-script.py", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\api.py", line 153, in <listcomp>
    for element in dom['elements']]
KeyError: 'assetId'

**Comment by balta2ar** [comment]
Use the very latest version from github, it should work.

**Comment by AhmedA-del** [comment]
i'm using the website 
what do you mean by the latest version

**Comment by balta2ar** [comment]
What website? I don't understand you.
I mean that you should clone this repository locally and run it. Yesterday I merged related pull request that should fix your issue. Update your local copy of the script.

**Comment by karlosc** [comment]
I just can not download , I get error unrecognized arguments : learning -how -to -learn.
this is what I do
coursera-dl -u username -p password  learning-how-to-learn

I do wrong ?
please

**Comment by GlowingCrystallineEntity** [comment]
+1, this doesn't work for me either, and may be the same issue I reported in #462 

Is this fixed in github, but not yet on the pip install?

Is it possibly related to the fact that this course doesn't technically start for 3+ days?  I'm not sure that's true of all these courses... and also, even though it says it's parsing an "on-demand" class, not all of these are on-demand.  Anyway, here's debug output for this course mentioned in this thread;

> coursera-dl --debug -n -- learning-how-to-learn

root[get_config_paths] Environment var(s) ['HOME'] not defined, skipping
root[authenticate_through_netrc] Trying netrc file C:\Users\Nagarjuna\.netrc
root[authenticate_through_netrc] Trying netrc file C:\Users\Nagarjuna\_netrc
root[main] Downloading class: learning-how-to-learn
root[download_class] Downloading old style class learning-how-to-learn
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file D:\DEFAUL~1\tmp\Nagarjuna_coursera_dl_cache\cookies\bawdyboatswain@gmail.com.txt into memor
root[get_cookies_from_cache] Loaded cookies from D:\DEFAUL~1\tmp\Nagarjuna_coursera_dl_cache\cookies\bawdyboatswain@gmail.com.txt
root[login] Initiating login.
root[login] Cleared .coursera.org cookies.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /learning-how-to-learn HTTP/1.1" 404 None
root[login] 404 Client Error: Not Found for url: https://class.coursera.org/learning-how-to-learn
root[download_class] Downloading new style (on demand) class learning-how-to-learn
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[login] Forging cookie header: csrftoken=bqGDXA6dHBkqebyRqRak; csrf2_token_srTZJ23O=PGPebY9NIrEFxSEc7KQucQi5.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/course/learning-how-to-learn HTTP/1.1" 200 None
root[get_on_demand_syllabus] Downloaded https://www.coursera.org/api/opencourse.v1/course/learning-how-to-learn (38534 bytes)
root[parse_on_demand_syllabus] Parsing syllabus of on-demand course. This may take some time, be patient ...
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/video/mGhggl_JEeSfFCIACxcQxA HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <mGhggl_JEeSfFCIACxcQxA>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <mGhggl_JEeSfFCIACxcQxA>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/openCourseAssets.v1/Yry0spSKEeW8oA5fR3afVQ HTTP/1.1" 200 None
root[_get_open_course_asset_ids] Parsing JSON for asset_id <Yry0spSKEeW8oA5fR3afVQ>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/assets.v1/XcOqP5SKEeWEzxLvpoXzuQ HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool[_make_request] "GET /api/openCourseAssets.v1/kMQyUZSLEeWj-hLVp2Pm8w HTTP/1.1" 200 None
root[_get_open_course_asset_ids] Parsing JSON for asset_id <kMQyUZSLEeWj-hLVp2Pm8w>.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 91, in login
    r.raise_for_status()
  File "C:\Python34\lib\site-packages\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/learning-how-to-learn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: learning-how-to-learn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)

**Comment by balta2ar** [comment]
This issue is a mix of various errors reported in a chaotic order.

1. If you get "error unrecognized arguments", run like this:

    > coursera-dl --debug -n -- learning-how-to-learn

2. If you get "KeyError: 'assetId'", use the latest version from github.
3. @GlowingCrystallineEntity  Regarding your latest track trace, it looks incomplete. Please check.

**Comment by GlowingCrystallineEntity** [comment]
I was able to d/l this course with the latest version (0.6.1) without (this) issue, so this issue looks solved.

**Comment by CharlesDerek** [comment]
> note that I write the user name not the email

How do you find your username?
