### ISSUE TITLE
Way to ignore only the video files from downloads?

### ISSUE THREAD

**Issue by abhi18av** [coursera-dl/coursera-dl#599]
This is a feature request regarding the ability to only download the non-video materials from the course.

I know that it's already quite easy to just download the subtitles or PPT's etc but they need to determined manually beforehand for a course. Perhaps, I might have overlooked this functionality ( if it already exists) but this would definitely make `coursera-dl` even more awesome and flexible to use.

Maybe a interactive/utility function that discovers/ prints/ asks about the exact content that is present in the course and the one's we'd like to download, would make for a great UI.

Are there any workarounds I can use in the meantime?

**Comment by balta2ar** [comment]
@abhi18av If you add `--cache-syllabus` option, course's syllabus will be saved to file `<course-name>-syllabus-parsed.json` in current directory. If you also add `--only-syllabus`, the script will stop after saving a syllabus to a file. If you run the script again with `--cache-syllabus`, it will read syllabus from the file instead of downloading it from Coursera again.

Using this two options you can preview materials that are available to download. In fact, you can adjust syllabus and remove unwanted materials. It may be not very convenient without good editor JSON support though.

There is a slight nuance. Certain materials are downloaded to memory during the parsing stage, for example quiz HTML texts and images.
