### ISSUE TITLE
Feature request. Change [-u USERNAME] to [-e EMAIL] 

### ISSUE THREAD

**Issue by bessarabov** [coursera-dl/coursera-dl#625]
### Subject of the issue

Here is my situation. I was running:

```
coursera-dl -u LOGIN_I_ALWAYS_USE -p COURSERA_PASSWORD --debug COURSE_NAME
```

but got the error:

```
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 400 None
root[main] Could not authenticate: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://www.coursera.org/api/login/v3
```

It took me some time to find out that I should not use my standard login, but my email address. After I figure out the source of my problem I've remembered that this is the second time I'm doing the same mistake.

So, my feature request is to make this script simplier to use. Deprecate `-u` option and remove it from help and make `-e` option that is described as `[-e EMAIL] ` in help message.

### Your environment
* Operating System (name/version): docker image python:3.6.0
* Python version: 3.6.0
* coursera-dl version: 0.9.0

**Comment by rbrito** [comment]
Hi, @bessarabov.

First of all, can you tell me the other ways that you can specify logins that you use? Which one would be those? Just curious.

Second, I think that I can change the description of the -u option so that it mentions email instead of whatever it shows now, but given the number of people using the script and used to the meaning of -u, changing it to a new option would be a disservice to our users when they upgrade the script from one version to another... Especially if they don't update in some time and skip some releases...

How does that sound as a compromise?

Thanks,

Rogério.

**Comment by rbrito** [comment]
Hi, @bessarabov.

First of all, can you tell me the other ways that you can specify logins that you use? Which one would be those? Just curious.

Second, I think that I can change the description of the -u option so that it mentions email instead of whatever it shows now, but given the number of people using the script and used to the meaning of -u, changing it to a new option would be a disservice to our users when they upgrade the script from one version to another... Especially if they don't update in some time and skip some releases...

How does that sound as a compromise?

Thanks,

Rogério.
