### ISSUE TITLE
Multi-thread downloading?

### ISSUE THREAD

**Issue by ziliangpeng** [coursera-dl/coursera-dl#85]
Currently downloading in 1 thread seems slow for me. Do you have the intention to make it multi-threaded?

**Comment by HelloCodeMing** [comment]
Hey, I have added a few lines to let it support multiple-threads downloading, and it works perfectly in my test. But maybe it could not work in python3, it failed to pass the build and test. If you would like to spend some free time dealing with this, things will be better.

**Comment by HelloCodeMing** [comment]
I hate python. I spend one hour to let it combatible with python3, pass the test in the end.

**Comment by victorwestmann** [comment]
Is this working already or still in tests? (Just reviewing the whole tickets here)

**Comment by rbrito** [comment]
@HelloCodeMing has kindly contributed a pull request (see #313) to implement this, but I have not yet had time to review it.

**Comment by balta2ar** [comment]
@rbrito @victorwestmann @HelloCodeMing @asiviero @ziliangpeng 

Guys, let's think about this feature from "ethical" point of view. I've been debugging coursera-dl on these days and I was running two instances of the script in parallel. Over time I started to get more and more 400 Bad Request replies. And I'm not the only one here: #459. Those were replies from API (not from cloudflare CDN) and I'm not sure about their reason. This may be throttling from Coursera side.

Are you sure having parallel downloads will not trigger more bans from Coursera side and degrade user experience? I totally understand that skilled users will find their way to parallelize the downloader anyway and we can't possibly forbid that. But is it really good idea to have it and to turn it on by default for all our vast users (I judge by the number of stars)?

Please don't get me wrong, I'm not strictly against it, I just don't want to abuse Coursera servers and I would like to discuss it first.

**Comment by victorwestmann** [comment]
I think @rbrito has a point.



--Victor Westmann

2016-06-14 9:10 GMT-03:00 Yuri Bochkarev <notifications@github.com>:

**Comment by rbrito** [comment]
@balta2ar, first of all and most prominently, I agree with the concept that we should not get Coursera's servers being hit hard.

This was less of a problem with the old-style courses, since with just one request, we could grab all the syllabus/index file and process it locally with as long as we wanted with BeautifulSoup.

Now, with the new-style courses, things are much harder connection-wise, since we need a lot of requests just to get the videos (let alone all the other material).

Perhaps where users would see some improvement in performance would be to make parallel the download of materials (after everything is parsed and the URLs are already known). This would be akin to the move from HTTP/1.0 to HTTP/1.1 with persistent connections.

On the other hand, it makes implementation, debugging etc. harder. I guess that we can make this a low-priority, wishlist bug that, perhaps, we may implement some time in the future...

Otherwise, we have other, more pressing things to fix.

BTW, thanks for all the activity, Yuri.

**Comment by balta2ar** [comment]
Implemented in version 0.7.0. Closing.
